### ISSUE TITLE
I need to understand what I am doing and what I am doing wrong

### ISSUE THREAD

**Issue by natalie-macpherson** [natalie-macpherson/dsn1676-assignment-5#1]

**Comment by natalie-macpherson** [comment]
I have watch all of the videos for the DOM. For some I have watch them multiple times but when I try the stuff it still does not work.

Also, for your office hours, I have classes during all the time except the Monday which has passed and I really do not feel comfortable leaving until the Monday it is due. I would be able to make the Wednesday time but for that day this week we are doing studio tours and I have to travel to the location.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Looking at the code I'd say the biggest issue is the Mustache template stuff—delete it.
I believe I introduced some material too early and I think it would be better without it.
_Refer to the e-mail I sent around._
